// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.5
// source: api/grpc_helper.proto

//包名

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GrpcHelper_ListService_FullMethodName    = "/api.GrpcHelper/ListService"
	GrpcHelper_Invoke_FullMethodName         = "/api.GrpcHelper/Invoke"
	GrpcHelper_RefreshService_FullMethodName = "/api.GrpcHelper/RefreshService"
	GrpcHelper_Test_FullMethodName           = "/api.GrpcHelper/Test"
)

// GrpcHelperClient is the client API for GrpcHelper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GrpcHelperClient interface {
	// 获取服务列表
	ListService(ctx context.Context, in *ListServiceRequest, opts ...grpc.CallOption) (*ListServiceReply, error)
	// 执行
	Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeReply, error)
	RefreshService(ctx context.Context, in *RefreshServiceRequest, opts ...grpc.CallOption) (*RefreshServiceReply, error)
	Test(ctx context.Context, in *TestMessage, opts ...grpc.CallOption) (*TestMessage, error)
}

type grpcHelperClient struct {
	cc grpc.ClientConnInterface
}

func NewGrpcHelperClient(cc grpc.ClientConnInterface) GrpcHelperClient {
	return &grpcHelperClient{cc}
}

func (c *grpcHelperClient) ListService(ctx context.Context, in *ListServiceRequest, opts ...grpc.CallOption) (*ListServiceReply, error) {
	out := new(ListServiceReply)
	err := c.cc.Invoke(ctx, GrpcHelper_ListService_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcHelperClient) Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeReply, error) {
	out := new(InvokeReply)
	err := c.cc.Invoke(ctx, GrpcHelper_Invoke_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcHelperClient) RefreshService(ctx context.Context, in *RefreshServiceRequest, opts ...grpc.CallOption) (*RefreshServiceReply, error) {
	out := new(RefreshServiceReply)
	err := c.cc.Invoke(ctx, GrpcHelper_RefreshService_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcHelperClient) Test(ctx context.Context, in *TestMessage, opts ...grpc.CallOption) (*TestMessage, error) {
	out := new(TestMessage)
	err := c.cc.Invoke(ctx, GrpcHelper_Test_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrpcHelperServer is the server API for GrpcHelper service.
// All implementations must embed UnimplementedGrpcHelperServer
// for forward compatibility
type GrpcHelperServer interface {
	// 获取服务列表
	ListService(context.Context, *ListServiceRequest) (*ListServiceReply, error)
	// 执行
	Invoke(context.Context, *InvokeRequest) (*InvokeReply, error)
	RefreshService(context.Context, *RefreshServiceRequest) (*RefreshServiceReply, error)
	Test(context.Context, *TestMessage) (*TestMessage, error)
	mustEmbedUnimplementedGrpcHelperServer()
}

// UnimplementedGrpcHelperServer must be embedded to have forward compatible implementations.
type UnimplementedGrpcHelperServer struct {
}

func (UnimplementedGrpcHelperServer) ListService(context.Context, *ListServiceRequest) (*ListServiceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListService not implemented")
}
func (UnimplementedGrpcHelperServer) Invoke(context.Context, *InvokeRequest) (*InvokeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Invoke not implemented")
}
func (UnimplementedGrpcHelperServer) RefreshService(context.Context, *RefreshServiceRequest) (*RefreshServiceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshService not implemented")
}
func (UnimplementedGrpcHelperServer) Test(context.Context, *TestMessage) (*TestMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Test not implemented")
}
func (UnimplementedGrpcHelperServer) mustEmbedUnimplementedGrpcHelperServer() {}

// UnsafeGrpcHelperServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GrpcHelperServer will
// result in compilation errors.
type UnsafeGrpcHelperServer interface {
	mustEmbedUnimplementedGrpcHelperServer()
}

func RegisterGrpcHelperServer(s grpc.ServiceRegistrar, srv GrpcHelperServer) {
	s.RegisterService(&GrpcHelper_ServiceDesc, srv)
}

func _GrpcHelper_ListService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcHelperServer).ListService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrpcHelper_ListService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcHelperServer).ListService(ctx, req.(*ListServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrpcHelper_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcHelperServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrpcHelper_Invoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcHelperServer).Invoke(ctx, req.(*InvokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrpcHelper_RefreshService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcHelperServer).RefreshService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrpcHelper_RefreshService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcHelperServer).RefreshService(ctx, req.(*RefreshServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrpcHelper_Test_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcHelperServer).Test(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrpcHelper_Test_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcHelperServer).Test(ctx, req.(*TestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// GrpcHelper_ServiceDesc is the grpc.ServiceDesc for GrpcHelper service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GrpcHelper_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.GrpcHelper",
	HandlerType: (*GrpcHelperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListService",
			Handler:    _GrpcHelper_ListService_Handler,
		},
		{
			MethodName: "Invoke",
			Handler:    _GrpcHelper_Invoke_Handler,
		},
		{
			MethodName: "RefreshService",
			Handler:    _GrpcHelper_RefreshService_Handler,
		},
		{
			MethodName: "Test",
			Handler:    _GrpcHelper_Test_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/grpc_helper.proto",
}
